#There are four 1 size ships, three 2 size ships, two 3 size ships and one 4 size ship

ships = [["A2", "A4"],
         ["C2", "C5"],
         ["F2", "G2"],
         ["I2", "I2"],
         ["H5", "I5"],
         ["B9", "B9"],
         ["F7", "F8"],
         ["J7", "J7"],
         ["I9", "I9"],
         ["D10", "F10"],
        ]